name: Bump Version, Build, Commit, and Release

# This workflow is triggered manually from the Actions tab
on:
  workflow_dispatch:

jobs:
  # This job builds the binaries first, based on the latest master commit
  build_binaries:
    name: Build Prebuilds (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'

      # Setup for Windows build
      - name: Setup MSBuild and Python for node-gyp
        if: matrix.os == 'windows-latest'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: microsoft/setup-msbuild@v2
        if: matrix.os == 'windows-latest'

      # Setup for Linux build
      - name: Install build tools (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y build-essential

      # Force a clean build to prevent caching issues
      - name: Clean Old Build Artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: rm -rf build prebuilds

      - name: Clean Old Build Artifacts (Windows)
        if: matrix.os == 'windows-latest'
        run: Remove-Item -Recurse -Force build, prebuilds -ErrorAction SilentlyContinue
      
      - name: Install dependencies
        run: npm install

      - name: Run prebuildify
        run: npm run prebuild

      - name: Upload Prebuild Artifact
        uses: actions/upload-artifact@v4
        with:
          name: prebuilds-${{ matrix.os }}
          path: prebuilds/

  # This job runs after the binaries are built. It combines them, versions,
  # commits, tags, and creates the final release.
  combine_and_release:
    name: Combine, Commit, Tag, and Release
    runs-on: ubuntu-latest
    needs: [build_binaries]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-prebuilds

      - name: Consolidate Binaries
        run: |
          echo "Removing existing prebuilds directory if it exists..."
          rm -rf prebuilds
          mkdir prebuilds
          echo "Copying new binaries from downloaded artifacts..."
          for dir in downloaded-prebuilds/*/; do
            cp -r "$dir"* prebuilds/
          done
          echo "Final consolidated contents of prebuilds directory:"
          ls -R prebuilds/

      - name: Configure Git User
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Check for Changes
        id: git_status
        run: |
          # The "M" status indicates a modified file (existing binary was updated)
          # The "??" status indicates a new file (binary was created from scratch)
          if git status --porcelain | grep -E " M |^\?\? "; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Version, Commit, and Tag
        id: npm_version
        if: steps.git_status.outputs.changes == 'true'
        run: |
          # Stage the prebuilt binaries
          git add prebuilds

          # Use npm version to bump package.json, create a commit, and tag it.
          # The commit will include both the package.json change AND the staged binaries.
          # Use 'minor' or 'major' here if you want to increment a different part of the version.
          npm version patch -m "ci: Bump version to %s and commit prebuilt binaries"
          
          # Push the new commit and the new tag to the master branch
          git push --follow-tags
          
          # Output the new tag for the release step
          echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
      
      - name: Create GitHub Release
        if: steps.npm_version.outputs.tag # Only run if a new tag was created
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.npm_version.outputs.tag }}
          release_name: Release ${{ steps.npm_version.outputs.tag }}
          body: |
            Automated release with pre-built binaries for Windows and Linux.
          draft: false
          prerelease: false

      - name: No Changes Detected
        if: steps.git_status.outputs.changes == 'false'
        run: echo "No changes to binaries found. Skipping version bump and release."