name: Build and Upload Pre-built Binaries

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build_binaries:
    name: Build Prebuilds (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'

      # Setup for Windows build
      - name: Setup MSBuild and Python for node-gyp
        if: matrix.os == 'windows-latest'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: microsoft/setup-msbuild@v2
        if: matrix.os == 'windows-latest'

      # Setup for Linux build
      - name: Install build tools (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y build-essential

      # Install dev dependencies, including 'prebuild'
      - name: Install dependencies
        run: npm install

      # 1. Generate the OS-specific binary in prebuilds/
      - name: Run prebuildify
        run: npm run prebuild

      # 2. Upload the entire prebuilds folder as an artifact.
      # The artifact name must be unique per job.
      - name: Upload Prebuild Artifact
        uses: actions/upload-artifact@v4
        with:
          name: prebuilds-${{ matrix.os }}
          path: prebuilds/
          
  # Add a new job to combine and commit the files
  combine_and_commit:
    name: Combine and Commit Binaries
    runs-on: ubuntu-latest
    # Wait for ALL matrix jobs to complete successfully
    needs: [build_binaries]
    
    steps:
      - uses: actions/checkout@v4
        with:
          # IMPORTANT: Fetch full history so we can commit back to the branch
          fetch-depth: 0 
          token: ${{ secrets.GITHUB_TOKEN }}
          
      # 1. Download all artifacts created by the matrix jobs
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-prebuilds

      # 2. Consolidate Binaries
      - name: Consolidate Binaries
        run: |
          # 1. Create the final destination directory
          mkdir -p prebuilds
          
          # 2. Move the contents (the platform folders: linux-x64, win32-x64) 
          # from their downloaded artifact folders into the clean prebuilds/ directory.
          mv downloaded-prebuilds/prebuilds-ubuntu-latest/* prebuilds/
          mv downloaded-prebuilds/prebuilds-windows-latest/* prebuilds/

          echo "Final consolidated contents of prebuilds directory:"
          ls prebuilds/

      # 3. Commit the new prebuilds to the Git repository
      - name: Commit and Push Binaries
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Stage the prebuilds directory.
          git add prebuilds
          
          # Fetch and checkout the branch the tag originated from. 
          # Assuming the source branch is 'main'. You may need to change 'main' to 'master'.
          git fetch origin ${{ github.ref_name }}
          git checkout ${{ github.ref_name }}

          # Check if there are any staged changes. If not, git commit will fail.
          # We run the commit and use '|| true' to prevent the overall step from failing
          # if the binaries were identical (nothing to commit).
          LATEST_VERSION=$(git describe --tags --abbrev=0)
          
          # Force a push, but only if there are actual changes staged (binaries exist and are new)
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "ci: Prebuilt binaries for ${LATEST_VERSION}"
            git push
          else
            echo "No new changes to binaries found. Skipping commit and push."
          fi
