name: Build and Upload Pre-built Binaries

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-upload:
    name: Prebuild for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      # Setup for Windows build
      - name: Setup MSBuild and Python for node-gyp
        if: matrix.os == 'windows-latest'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: microsoft/setup-msbuild@v2
        if: matrix.os == 'windows-latest'

      # Setup for Linux build
      - name: Install build tools (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y build-essential

      # Install dev dependencies, including 'prebuild'
      - name: Install dependencies
        run: npm install

      # This is the key step. 'prebuild' will:
      # 1. Compile the addon using node-gyp.
      # 2. Package it into a correctly named .tar.gz file.
      # 3. Upload it to a draft release on GitHub.
      - name: Compile, package, and upload binary
        run: npx prebuild --runtime napi --all --upload ${{ secrets.GITHUB_TOKEN }} --tag-prefix v